POST http://localhost:3003/api/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbW8iLCJpZCI6IjYzZmZhM2MxZjMzN2E3NmE4ZTIyZjQ4NyIsImlhdCI6MTY3ODExNzI2NiwiZXhwIjoxNjc4MTE5MDY2fQ.jsLWZyeZgA97bVqlRH99EpAvqW_5hnENmz9yCrwlD1Q

{
  "title": "stay the w2ay you areww",
  "fileId": "4_z82e021a3e772aea4942481620a1b_f10557543f9226aeb4a_d20230304_m030715_c005_v0501003_t0025_u01677899235238",
  "duration" : 223
}