POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hehe",
  "name": "shamimomo",
  "email": "shamikohehe@gmail.com",
  "password": "shamimomo"
}

### 
PUT http://localhost:3003/api/users/63ffa3c1f337a76a8e22f487
Content-Type: application/json

{
  "bio": "huehuehuehue"
}

###
GET http://localhost:3003/api/users
